# Generated by Django 4.0.6 on 2023-03-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type_name', models.CharField(max_length=20)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField(max_length=100)),
                ('gender', models.CharField(max_length=2)),
                ('isactive', models.BooleanField()),
                ('contact_number', models.IntegerField()),
                ('sms_notification_active', models.BooleanField()),
                ('email_notification_active', models.BooleanField()),
                ('user_image', models.ImageField(blank=True, max_length=200, upload_to='')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('user_type_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usertype', to='spacificmanpower.user_type')),
            ],
        ),
    ]
