# Generated by Django 4.0.6 on 2023-03-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_stream_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('profile_description', models.CharField(max_length=1000)),
                ('establishment_date', models.DateTimeField()),
                ('company_website_url', models.CharField(max_length=500)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('business_stream_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='business_stream_id', to='spacificmanpower.business_stream')),
            ],
        ),
    ]
