# Generated by Django 4.0.6 on 2023-04-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_detail',
            name='institute_university_name',
            field=models.CharField(max_length=100),
        ),
    ]
