# Generated by Django 4.0.6 on 2023-04-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post_activity',
            name='status',
        ),
    ]
