# Generated by Django 4.0.6 on 2023-04-19 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='company_image_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_image_id', to='spacificmanpower.company_image'),
        ),
    ]
