# Generated by Django 4.0.6 on 2023-04-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_us',
        ),
    ]
