# Generated by Django 4.0.6 on 2023-04-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='user_image',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
