# Generated by Django 4.0.6 on 2023-04-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post_activity',
            name='userstatus',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
