# Generated by Django 4.0.6 on 2023-03-31 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0002_business_stream_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_stream',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business_stream',
            name='modifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='company_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_image', models.ImageField(blank=True, max_length=200, upload_to='')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='spacificmanpower.company')),
            ],
        ),
    ]
