# Generated by Django 4.0.6 on 2023-05-12 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0002_alter_seeker_profile_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
