# Generated by Django 4.0.6 on 2023-04-19 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0002_job_post_company_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='company_image_id',
        ),
    ]
