# Generated by Django 4.0.6 on 2023-05-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0002_alter_job_post_activity_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='last_job_apply_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
