# Generated by Django 4.0.6 on 2023-04-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0002_alter_education_detail_institute_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_detail',
            name='completion_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='education_detail',
            name='starting_date',
            field=models.DateTimeField(),
        ),
    ]
