# Generated by Django 4.0.6 on 2023-04-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0002_remove_job_post_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post_activity',
            name='status',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
