# Generated by Django 4.0.6 on 2023-05-19 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0002_alter_job_post_activity_job_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post_activity',
            name='job_post_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_post_id', to='spacificmanpower.job_post'),
        ),
    ]
