# Generated by Django 4.0.6 on 2023-04-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0003_job_post_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post_skill_set',
            name='skill_set_id',
            field=models.ForeignKey(blank=True, default=None, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_set_id', to='spacificmanpower.skill_set'),
        ),
    ]
