# Generated by Django 4.0.6 on 2023-03-31 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0003_business_stream_createddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='education_detail',
            fields=[
                ('user_account_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_account_id', serialize=False, to='spacificmanpower.user_account')),
                ('certificate_degree_name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('institute_university_name', models.CharField(max_length=50)),
                ('starting_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True)),
                ('percentage', models.IntegerField(blank=True)),
                ('cgpa', models.IntegerField(blank=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='experience_detail',
            fields=[
                ('user_account_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_account_ids', serialize=False, to='spacificmanpower.user_account')),
                ('is_current_job', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('job_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('job_location_city', models.CharField(max_length=50)),
                ('job_location_state', models.CharField(max_length=50)),
                ('job_location_country', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=4000)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
