# Generated by Django 4.0.6 on 2023-05-05 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0003_alter_user_log_last_job_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeker_profile',
            name='user_account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_account_idss', serialize=False, to='spacificmanpower.user_account', unique=True),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='user_account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_account_id', serialize=False, to='spacificmanpower.user_account', unique=True),
        ),
    ]
