# Generated by Django 4.0.6 on 2023-05-19 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0003_alter_job_post_activity_job_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='user_account_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_contact_us', to='spacificmanpower.user_account'),
        ),
    ]
