# Generated by Django 4.0.6 on 2023-04-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0003_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='recservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=400)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('user_account_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_recservice', to='spacificmanpower.user_account')),
            ],
        ),
    ]
