# Generated by Django 4.0.6 on 2023-04-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0003_alter_education_detail_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='salary',
            field=models.IntegerField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='skill_set',
            name='skill_set_name',
            field=models.CharField(max_length=200),
        ),
    ]
