# Generated by Django 4.0.6 on 2023-05-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0003_alter_user_log_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_detail',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
