# Generated by Django 4.0.6 on 2023-05-05 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0004_alter_job_post_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_profile',
            name='user_account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_account_idss', serialize=False, to='spacificmanpower.user_account'),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='user_account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_account_id', serialize=False, to='spacificmanpower.user_account'),
        ),
    ]
