# Generated by Django 4.0.6 on 2023-03-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0004_education_detail_experience_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='seeker_profile',
            fields=[
                ('user_account_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_account_idss', serialize=False, to='spacificmanpower.user_account')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('current_salary', models.IntegerField(blank=True)),
                ('is_annually_monthly', models.BooleanField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='skill_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_set_name', models.CharField(max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='seeker_skill_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_set_id', models.IntegerField()),
                ('skill_level', models.IntegerField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('user_account_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_idsss', to='spacificmanpower.user_account')),
            ],
        ),
    ]
