# Generated by Django 4.0.6 on 2023-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0004_alter_contact_us_user_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post_activity',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_post_activity',
            name='country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_post_activity',
            name='enquiry',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
