# Generated by Django 4.0.6 on 2023-04-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0004_alter_job_post_skill_set_skill_set_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='user_image',
            field=models.ImageField(blank=True, default='', max_length=200, upload_to=''),
            preserve_default=False,
        ),
    ]
