# Generated by Django 4.0.6 on 2023-04-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0004_alter_job_post_salary_alter_skill_set_skill_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='salary',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
