# Generated by Django 4.0.6 on 2023-04-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0005_experince_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='experince_type_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experince_type_id', to='spacificmanpower.experince_type'),
        ),
    ]
