# Generated by Django 4.0.6 on 2023-07-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0005_job_post_activity_city_job_post_activity_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
