# Generated by Django 4.0.6 on 2023-04-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0005_alter_user_account_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience_detail',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience_detail',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
