# Generated by Django 4.0.6 on 2023-04-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0005_alter_job_post_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience_detail',
            name='is_current_job',
        ),
    ]
