# Generated by Django 4.0.6 on 2023-05-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
