# Generated by Django 4.0.6 on 2023-04-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0006_remove_experience_detail_is_current_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience_detail',
            name='is_current_job',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
