# Generated by Django 4.0.6 on 2023-08-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0006_company_company_location_company_company_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
    ]
