# Generated by Django 4.0.6 on 2023-04-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0006_alter_user_account_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='username',
            field=models.CharField(default='', max_length=122),
            preserve_default=False,
        ),
    ]
