# Generated by Django 4.0.6 on 2023-04-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0006_job_post_experince_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='salary',
            field=models.IntegerField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
