# Generated by Django 4.0.6 on 2023-04-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0006_alter_experience_detail_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience_detail',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience_detail',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
