# Generated by Django 4.0.6 on 2023-04-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0007_user_account_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_account',
            old_name='username',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user_account',
            name='last_name',
            field=models.CharField(default='', max_length=122),
            preserve_default=False,
        ),
    ]
