# Generated by Django 4.0.6 on 2023-08-16 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0007_alter_job_post_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='company_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='spacificmanpower.company'),
        ),
    ]
