# Generated by Django 4.0.6 on 2023-05-17 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0008_job_post_activity_applicant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post_activity',
            name='user_account_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_idssss', to='spacificmanpower.user_account'),
        ),
    ]
