# Generated by Django 4.0.6 on 2023-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0008_rename_username_user_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
