# Generated by Django 4.0.6 on 2023-08-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0009_job_post_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_qualification',
            field=models.CharField(max_length=1200),
        ),
    ]
