# Generated by Django 4.0.6 on 2023-05-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0009_alter_job_post_activity_user_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='user_account_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_subscribe', to='spacificmanpower.user_account'),
        ),
    ]
