# Generated by Django 4.0.6 on 2023-05-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0010_alter_subscribe_user_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recservice',
            name='user_account_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_recservice', to='spacificmanpower.user_account'),
        ),
    ]
