# Generated by Django 4.0.6 on 2023-04-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0010_alter_user_account_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
