# Generated by Django 4.0.6 on 2023-04-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0011_alter_experience_detail_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_profile',
            name='current_salary',
            field=models.IntegerField(null=True),
        ),
    ]
