# Generated by Django 4.0.6 on 2023-04-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0011_alter_experience_detail_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education_detail',
            name='institute_university_name',
        ),
        migrations.AlterField(
            model_name='seeker_profile',
            name='current_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
