# Generated by Django 4.0.6 on 2023-04-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0012_alter_user_account_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='isactive',
            field=models.BooleanField(blank=True),
        ),
    ]
