# Generated by Django 4.0.6 on 2023-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0012_remove_education_detail_institute_university_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education_detail',
            name='institute_university_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
