# Generated by Django 4.0.6 on 2023-08-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0012_alter_job_post_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_qualification',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
