# Generated by Django 4.0.6 on 2023-04-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0013_education_detail_institute_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_profile',
            name='current_salary',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
