# Generated by Django 4.0.6 on 2023-04-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0013_alter_user_account_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='last_login_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
