# Generated by Django 4.0.6 on 2023-04-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0013_alter_seeker_profile_current_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_detail',
            name='completion_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education_detail',
            name='starting_date',
            field=models.DateField(),
        ),
    ]
