# Generated by Django 4.0.6 on 2023-04-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0014_alter_education_detail_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_detail',
            name='completion_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='education_detail',
            name='starting_date',
            field=models.DateTimeField(),
        ),
    ]
