# Generated by Django 4.0.6 on 2023-08-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0014_alter_job_post_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_qualification',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
