# Generated by Django 4.0.6 on 2023-04-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0015_alter_user_log_last_job_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='establishment_date',
            field=models.DateField(),
        ),
    ]
