# Generated by Django 4.0.6 on 2023-04-04 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0016_alter_company_establishment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_image',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company_image',
            name='company_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_id_companyimage', to='spacificmanpower.company'),
        ),
    ]
