# Generated by Django 4.0.6 on 2023-04-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0017_company_company_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_image',
        ),
        migrations.AlterField(
            model_name='company_image',
            name='company_image',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
    ]
