# Generated by Django 4.0.6 on 2023-08-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0017_alter_job_post_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_qualification',
            field=models.JSONField(blank=True, max_length=3000, null=True),
        ),
    ]
