# Generated by Django 4.0.6 on 2023-04-04 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0018_remove_company_company_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_stream_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_stream_id', to='spacificmanpower.business_stream'),
        ),
    ]
