# Generated by Django 4.0.6 on 2023-04-05 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0019_alter_company_business_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_image',
            name='company_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_id_company_image', to='spacificmanpower.company'),
        ),
    ]
