# Generated by Django 4.0.6 on 2024-04-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0020_alter_job_post_activity_phone_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_stream',
            name='business_stream_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyimage',
            field=models.ImageField(blank=True, max_length=200, upload_to='companylogo/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='profile_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education_detail',
            name='certificate_degree_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='education_detail',
            name='institute_university_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education_detail',
            name='major',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='experience_detail',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience_detail',
            name='job_location_city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience_detail',
            name='job_location_country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience_detail',
            name='job_location_state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience_detail',
            name='job_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experince_type',
            name='experince_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job_location',
            name='city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job_location',
            name='country',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job_location',
            name='state',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job_location',
            name='street_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job_location',
            name='zip',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job_post',
            name='job_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='job_post',
            name='job_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job_post_activity',
            name='applicant_email',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='job_post_activity',
            name='applicant_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job_post_activity',
            name='city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job_post_activity',
            name='country',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job_post_activity',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job_post_skill_set',
            name='skill_set_id',
            field=models.ForeignKey(blank=True, default=None, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_set_id', to='spacificmanpower.skill_set'),
        ),
        migrations.AlterField(
            model_name='job_type',
            name='job_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recservice',
            name='email',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='recservice',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='seeker_profile',
            name='currency',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='seeker_profile',
            name='first_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='seeker_profile',
            name='is_annually_monthly',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='seeker_profile',
            name='last_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='trending_news',
            name='news_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trending_news',
            name='news_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='trending_news',
            name='news_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='contact_number',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='last_name',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='subscribed_email_id',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='user_image',
            field=models.ImageField(blank=True, max_length=200, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='user_type_name',
            field=models.CharField(max_length=200),
        ),
    ]
