# Generated by Django 4.0.6 on 2023-04-05 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0020_alter_company_image_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='posted_by_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by_id', to='spacificmanpower.job_post_activity'),
        ),
    ]
