# Generated by Django 4.0.6 on 2023-04-05 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0021_alter_job_post_posted_by_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='posted_by_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by_id', to='spacificmanpower.job_post_activity'),
        ),
    ]
