# Generated by Django 4.0.6 on 2024-05-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0023_alter_gallery_image_alter_user_account_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_type_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_type_id', to='spacificmanpower.job_type'),
        ),
    ]
