# Generated by Django 4.0.6 on 2023-04-05 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0023_alter_seeker_profile_user_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_profile',
            name='user_account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_account_idss', serialize=False, to='spacificmanpower.user_account'),
        ),
    ]
