# Generated by Django 4.0.6 on 2023-04-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0024_alter_seeker_profile_user_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_post',
            name='country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_post',
            name='state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_post',
            name='street_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_post',
            name='zip',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
