# Generated by Django 4.0.6 on 2023-04-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0025_job_post_city_job_post_country_job_post_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post_activity',
            name='job_post_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_post_id', to='spacificmanpower.job_post'),
        ),
        migrations.AlterField(
            model_name='job_post_activity',
            name='user_account_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_idssss', to='spacificmanpower.user_account'),
        ),
    ]
