# Generated by Django 4.0.6 on 2023-04-05 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0027_remove_job_post_city_remove_job_post_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job_post_skill_set',
            name='job_post_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_post_id_job_post_skill_set', to='spacificmanpower.job_post'),
        ),
    ]
