# Generated by Django 4.0.6 on 2023-04-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0029_alter_job_post_activity_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_profile',
            name='is_annually_monthly',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
