# Generated by Django 4.0.6 on 2023-04-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0031_trending_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker_profile',
            name='createdDate',
        ),
    ]
