# Generated by Django 4.0.6 on 2023-04-06 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0032_remove_seeker_profile_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker_profile',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
