# Generated by Django 4.0.6 on 2023-04-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0033_seeker_profile_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_profile',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
