# Generated by Django 4.0.6 on 2023-04-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0036_alter_seeker_skill_set_skill_set_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending_news',
            name='news_image',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
    ]
