# Generated by Django 4.0.6 on 2023-04-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0037_alter_trending_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending_news',
            name='news_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
