# Generated by Django 4.0.6 on 2023-04-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0038_alter_trending_news_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker_profile',
            name='uploaded_cv',
            field=models.FileField(null=True, blank=True,default=None, upload_to=''),
        ),
    ]
