# Generated by Django 4.0.6 on 2023-04-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0043_alter_seeker_profile_uploaded_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_profile',
            name='uploaded_cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
