# Generated by Django 4.0.6 on 2023-04-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0044_alter_seeker_profile_uploaded_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker_profile',
            name='uploaded_cv',
        ),
    ]
