# Generated by Django 4.0.6 on 2023-04-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0046_seeker_profile_uploaded_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='job_title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
