# Generated by Django 4.0.6 on 2023-04-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0047_job_post_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_image',
            old_name='company_image',
            new_name='companyimage',
        ),
    ]
