# Generated by Django 4.0.6 on 2023-04-17 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0048_rename_company_image_company_image_companyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_account',
            old_name='email',
            new_name='email_address',
        ),
    ]
