# Generated by Django 4.0.6 on 2023-04-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0049_rename_email_user_account_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='company_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_image', to='spacificmanpower.company_image'),
        ),
    ]
