# Generated by Django 4.0.6 on 2023-04-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0051_alter_user_log_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='email_address',
            field=models.CharField(max_length=122, unique=True),
        ),
    ]
