# Generated by Django 4.0.6 on 2023-04-19 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0054_remove_company_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='job_post_skill_set',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_post_skill_set', to='spacificmanpower.job_post_skill_set'),
        ),
    ]
