# Generated by Django 4.0.6 on 2023-04-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacificmanpower', '0055_job_post_job_post_skill_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='job_post_skill_set',
        ),
    ]
